image: python:3.8.5

stages:
  - safety
  - lint
  - build
  - test
  - production

before_script:
  - pip install -r ./requirements.txt
  - apt-get update

Safety:
  stage: safety
  script:
    - pip install safety
    - safety check --full-report -r requirements.txt

PyLint:
  stage: lint
  script:
    - pip install pylint
    - error_count=$(pylint --errors-only --disable='E0401' --disable='F0001' src/ | wc -l)
    - if [ $error_count -ge 1 ];then
    - exit 1
    - fi
    - if [ $error_count -eq 0 ];then
    - exit 0
    - fi

build:
  stage: build
  script:
    - pip install ./src/

test:
  stage: test
  script:
    - apt-get install -y ffmpeg
    - cd ./tests
    - python -m unittest

production:
  type: deploy
  before_script:
    - apt-get update
  stage: production
  image: ruby:latest
  script:
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - main
