image: python:3.8.5

stages:
  - build
  - test

before_script:
  - pip install -r ./install/requirements.txt
  - apt-get update

build:
  stage: build
  script:
    - pip install ./src/

test:
  stage: test
  script:
    - apt-get install -y ffmpeg
    - cd ./tests
    - python -m unittest
